### ISSUE TITLE
How to install the LDAP module？resolved

### ISSUE THREAD

**Issue by ax2009live** [Wadoom/wordpress-http2#1]
Wadoom / wordpress-http2 is great, SSL and http / 2 is supported by default

How to install the LDAP module？

I use the official image，Enter the container，It will be OK after restart，
  apt-get update \
  apt-get install -y libldap2-dev \
  rm -rf /var/lib/apt/lists/* \
  docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/ \
  docker-php-ext-install ldap \
  apt-get purge -y --auto-remove libldap2-dev

Wadoom /wordpress-http2   The container does not have “docker PHP ext configure“  and “docker PHP ext install”
What should I do？
thank you！

**Comment by ax2009live** [comment]
I solved the problem myself：

Boot the container using the official image “wordpress:5.6”，the containerin‘s directory / urs / local / bin,copy the three file to the host  - /root/apache2/
“docker-php-ext-configure"  "docker-php-source" "docker-php-ext-install"

download https://www.php.net/distributions/php-7.4.15.tar.xz , renamed php.tar.xz, Move to the directory  “/root/apache2/”

Create a gateway：
docker network create --driver bridge --subnet=172.18.0.0/24 --gateway=172.18.0.1 mynet

Create the container,
`docker run  -d 
            --restart=always 
           --name wordpress 
          -v /root/apache2:/etc/apache2/sites-enabled 
          -v /root/nginx/wordpress:/var/www/html 
          -v /root/nginx/certs:/root/nginx/certs
         -p 443:443 
         --network=mynet --ip 172.18.0.20 
         w4d00m/wordpress-http2:wp-5.5`


Enter the  container： docker exec -it wordpress  /bin/bash
cp /etc/apache2/sites-enabled/docker-php* /usr/local/bin/
cp /etc/apache2/sites-enabled/php.tar.xz /usr/src/
apt-get update -y
apt-get install -y php-dev
apt-get install -y xz-utils
apt-get install -y libldap2-dev
rm -rf /var/lib/apt/lists/*
/usr/local/bin/docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/
/usr/local/bin/docker-php-ext-install ldap
apt-get purge -y --auto-remove libldap2-dev

restart the container, LDAP has been installed；

**Comment by Wadoom** [comment]
Thank you for such great work!
